version: "3"

services:
  tasks_queue:
    image: rabbitmq:3.7.8-management-alpine
    network_mode: host

  releases_db:
    image: mongo:4.0.1-xenial
    network_mode: host

  topics_db:
    image: neo4j:3.4.7
    network_mode: host
    environment:
      NEO4J_AUTH: none
