version: "3"

services:
  metrics_collector:
    image: telegraf:1.7.4-alpine
    network_mode: host
    volumes:
    - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - /var/run/docker.sock:/var/run/docker.sock

  metrics_db:
    image: influxdb:1.6.2-alpine
    network_mode: host

  metrics_visualization:
    image: grafana/grafana:5.2.4
    network_mode: host
